server:
 port: 9191

spring:
  application:
    name: CHECK-SERVICE
    
#eureka service registry config  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
  
  
  
    
#actuator config     
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health        
  endpoint:
    health:
      show-details: always 
        
        
#resilience4J
resilience4j:
  circuitbreaker:
    instances:
      check-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        
        
  retry:
    instances:
      check-service:
#   real example 3 max attemps and 2 sec wait-duration
        max-attempts: 5
        wait-duration: 10s
      